# A

In [1]:
import numpy as np

def convolve_1d(signal, kernel):
    kernel_size = len(kernel)
    signal_size = len(signal)
    output_size = signal_size - kernel_size + 1
    output = np.zeros(output_size)
    for i in range(output_size):
        output[i] = np.sum(signal[i:i+kernel_size] * kernel)
    return output

# Define input signal and kernel
signal = np.array([1, 2, 3, 4, 5, 6])
kernel = np.array([0.5, 0.5])

# Perform 1D convolution
output = convolve_1d(signal, kernel)

print("Input Signal:", signal)
print("Kernel:", kernel)
print("Output after 1D convolution:", output)

import numpy as np

def convolve_2d(image, kernel):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    output_height = image_height - kernel_height + 1
    output_width = image_width - kernel_width + 1
    output = np.zeros((output_height, output_width))
    for i in range(output_height):
        for j in range(output_width):
            output[i, j] = np.sum(image[i:i+kernel_height, j:j+kernel_width] * kernel)
    return output

# Define input image and kernel
image = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]])

# Perform 2D convolution
output = convolve_2d(image, kernel)

print("Input Image:\n", image)
print("Kernel:\n", kernel)
print("Output after 2D convolution:\n", output)


Input Signal: [1 2 3 4 5 6]
Kernel: [0.5 0.5]
Output after 1D convolution: [1.5 2.5 3.5 4.5 5.5]
Input Image:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Kernel:
 [[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
Output after 2D convolution:
 [[-6.]]


# B

In [3]:
from PIL import Image, ImageFilter

In [6]:
image = Image.open('dog.jpeg')

# Apply a 3x3 low-pass filter (smoothing filter)
smoothed_image = image.filter(ImageFilter.BoxBlur(3))

# Display the original and smoothed images
image.show(title='Original Image')
smoothed_image.show(title='Smoothed Image')


from PIL import Image, ImageFilter

# Open the input image
image = Image.open('dog.jpeg')

# Apply a 3x3 high-pass filter (sharpening filter)
sharpened_image = image.filter(ImageFilter.SHARPEN)

# Display the original and sharpened images
image.show(title='Original Image')
sharpened_image.show(title='Sharpened Image')
